export type MediaKitType = {
    id: string
    name: string,
    instagram: string,
    profile_picture: string
    posts: number,
    followers: number,
    location: string,
    bio: string,
    short_name: string,
    engagement_rate: number,
    avg_likes: number,
    avg_comments: number,
    avg_story_view: number,
    impressions: number,
    stats: {
        series: {name: string, percentage: number}[],
        ages: {name: string, percentage: number}[],
        country: {name: string, percentage: number}[],
    }
}

export type MediaKitDBType = {
    id: string,
    name: string,
    instagram: string,
    profile_picture: string
    posts: number,
    followers: number,
    location: string,
    bio: string,
    short_name: string,
    engagement_rate: number,
    avg_likes: number,
    avg_comments: number,
    avg_story_view: number,
    impressions: number,
    series_name_1: string,
    series_name_2: string,
    series_name_3: string,
    series_name_4: string,
    series_name_5: string,
    series_value_1: number,
    series_value_2: number,
    series_value_3: number,
    series_value_4: number,
    series_value_5: number,
    age_name_1: string,
    age_name_2: string,
    age_name_3: string,
    age_name_4: string,
    age_name_5: string,
    age_value_1: number,
    age_value_2: number,
    age_value_3: number,
    age_value_4: number,
    age_value_5: number,
    country_name_1: string,
    country_name_2: string,
    country_name_3: string,
    country_name_4: string,
    country_name_5: string,
    country_value_1: number,
    country_value_2: number,
    country_value_3: number,
    country_value_4: number,
    country_value_5: number,
}